(
    RESIZE_DIMENSIONS, 
    RESIZE_IMAGE, 
    COMPRESS_IMAGE, 
    GET_NEW_IMG_FORMAT, 
    GET_NEW_IMG_FORMAT_FILE, 
    GET_NEW_VID_FORMAT, 
    GET_NEW_VID_FILE, 
    GET_AUDIO_VID,
    GET_ACCELERATE_VID_FACTOR,
    GET_ACCELERATE_VID_FILE,
) = range(10)
